#!/usr/bin/env python3
"""Derive a default LED position map for the Lily58 from its key geometry.

The firmware cannot know where a strip was routed, so this assumes the common
arrangement: 36 LEDs snaked under each half's key field in a 6x6 grid. It is a
starting point, not a measurement -- correct it against your own board.

Units: about 10 per LED spacing, which leaves sub-LED resolution for smooth
wavefronts while keeping the devicetree integers small.
"""

import json
import pathlib
import subprocess
import sys

COLS, ROWS = 6, 6
PER_HALF = COLS * ROWS
PITCH = 10                 # units between adjacent LEDs
GAP = 30                   # units between the two halves

root = pathlib.Path(__file__).resolve().parent.parent
keys = json.loads((root / "sim" / "web" / "lily58-keys.json").read_text())

# Aspect ratio of each half's key field, so the grid is not square if the
# board is not.
left = [k for k in keys if k["x"] < 800]
w = max(k["x"] + k["w"] for k in left) - min(k["x"] for k in left)
h = max(k["y"] + k["h"] for k in left) - min(k["y"] for k in left)

span_x = (COLS - 1) * PITCH
span_y = round(span_x * h / w / (ROWS - 1)) * (ROWS - 1)

def half(origin_x):
    out = []
    for i in range(PER_HALF):
        row = i // COLS
        col = i % COLS
        if row % 2 == 1:                     # serpentine, as most strips run
            col = COLS - 1 - col
        out.append((origin_x + col * span_x // (COLS - 1),
                    row * span_y // (ROWS - 1)))
    return out

positions = half(0) + half(span_x + GAP)

# Wrap at a readable width, keeping each x,y pair on one line.
chunks, line = [], []
for x, y in positions:
    line.append(f"{x} {y}")
    if len(line) == 6:
        chunks.append("  ".join(line)); line = []
if line:
    chunks.append("  ".join(line))

cont = " \\\n"
body = cont.join("            " + c for c in chunks)

text = f"""/*
 * Copyright (c) 2026 The ZMK VFX Contributors
 *
 * SPDX-License-Identifier: MIT
 *
 * Default LED positions for a Lily58, for effects that radiate.
 *
 * Generated by sim/derive-positions.py. The firmware cannot know how a strip
 * was routed, so this assumes the common arrangement: {PER_HALF} LEDs snaked under
 * each half's key field in a {COLS}x{ROWS} grid, with the halves side by side. It is
 * a starting point, not a measurement.
 *
 * Units are about {PITCH} per LED spacing, which is the convention the effect
 * distance properties are tuned for.
 *
 *   #include <vfx/lily58-positions.dtsi>
 *
 *   &vfx_engine {{
 *       pixel-positions = <VFX_LILY58_POSITIONS>;
 *   }};
 *
 * If ripples radiate in the wrong shape on your board, this list is the thing
 * to correct: replace it with your own x,y pairs, one per pixel across the
 * whole keyboard, in strip order.
 */

#pragma once

#define VFX_LILY58_POSITIONS \\
{body}
"""

dest = root / "dts" / "vfx" / "lily58-positions.dtsi"
dest.write_text(text)
print(f"wrote {dest} ({len(positions)} pixels, x 0..{max(x for x,_ in positions)}, "
      f"y 0..{max(y for _,y in positions)})")
